### ISSUE TITLE
write18 is disabled

### ISSUE THREAD

**Issue by higgins29200** [overleaf/toolkit#11]
Hy,
I just discovered the possibility of overleaf and I installed an instanced today. Everything work fine but I'm using in all my project build on miktex the tks-fct library to draw functions. It works well on miktex and I try on overleaf online and it worked well too.

But when I try to compile on my own sharelatex instance following your docker install guide, I can't compil the project. In the log, I can see that "restricted \write18 enable". I don't have the problem on the online version.
I tried to use a "texmkrc" file but it has no effect on the compilation process.

In installed all library using full-scheme and gnuplot in the sharelatex docker.

Where can I say that I want to compile with write18 enabled ?

Thank's a lot

**Comment by ShaneKilkelly** [comment]
cc @emcsween, @mserranom , any idea why this would be the case? I couldn't find anything in the code that disables `\write18` explicitely.

**Comment by mserranom** [comment]
@higgins29200 if you can provide a sample project that would be useful.

**Comment by higgins29200** [comment]
Hy,
ok, i found where \write18 was disabled but forgot where in modify the script. I will search again but the issue can be close. It works know.
