### ISSUE TITLE
Support for `docker compose` instead of `docker-compose`

### ISSUE THREAD

**Issue by benjcabalona1029** [overleaf/toolkit#119]
This should be a really simple fix, by maybe adding a try catch logic at `bin/docker-compose`.

**Comment by aeaton-overleaf** [comment]
The [recommendation from Docker](https://github.com/docker/roadmap/issues/257#issue-992637043), during the transition from Docker Compose v1 to v2, is for users to alias `docker-compose` to `docker compose`.

Once everyone's migrated to Docker Compose v2, then scripts can be updated to use `docker compose`.
