### ISSUE TITLE
Failed to complete first installation of overleaf

### ISSUE THREAD

**Issue by iacchi** [overleaf/toolkit#12]
Hello,
I'm completely new to docker in general, so this might just be me being stupid about things (sorry in advance in that case). However: I'm trying to install overleaf community edition on my server, where there's already a webserver running (i.e. ports 80 and 443 are busy). I'm following this guide https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md to start overleaf for the first time; so far I have not touched the config files. When I run bin/up the script starts downloading the required docker images (mongo/redis and sharelatex), however at a certain point I get this error:

```
Recreating sharelatex ... error

ERROR: for sharelatex  Cannot start service sharelatex: driver failed programming external connectivity on endpoint sharelatex (b163548cf935c8a51c02a9d92887eeec373f7102dd659388be79145f688b88ad): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for sharelatex  Cannot start service sharelatex: driver failed programming external connectivity on endpoint sharelatex (b163548cf935c8a51c02a9d92887eeec373f7102dd659388be79145f688b88ad): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

Which I guess it's due to the fact that port 80 is already taken by the nginx webserver running on the machine. How do I tell the docker image to use a different port? Or am I doing something else wrong? The main system is based on Debian Stable (Buster).

**Comment by iacchi** [comment]
Looking at the source code of the script, I noticed that it calls $TOOLKIT_ROOT/lib/docker-compose.base.yml for the configuration, and that file contains this configuration:

```
        ports:
            - 80:80
```

So I created the filed config/docker-compose.override.yml and I put in there:

```
version: '2.2'
services:
    sharelatex:
        ports:
            - 85:80
```

So that it would bind on port 85 on the host machine, but when I run bin/up again it still failed with the same error as above. Because I wasn't sure of the correct port order number, I've also changed the override file with ports 80:85, but on running the up script the error remains.

**Comment by iacchi** [comment]
I can't seem to be able to edit previous comments, so I'll create another one. Out of spite, I've put the 85:80 ports directly in docker-compose.base.yml and the container started without problems. So, it seems the override contained in docker-compose.override.yml doesn't really work (which then makes me think if it'll work for the texlive upgrade as explained here: md )

**Comment by Leptopoda** [comment]
+1 for me

Basic port configuration is missing I'm the docs. And doesn't work with a docker-compose in ./config as said by @iacchi

**Comment by ShaneKilkelly** [comment]
Thanks for the report folks :+1: , I will look into adding a way to configure ports more easily.

**Comment by iacchi** [comment]
Thank you @ShaneKilkelly for looking into this. I think the best solution would be for the override in the docker-compose.override.yml file to work would be the easiest solution for everyone. And not just for the port parameter, but for any parameter that might be inside the docker-compose.base.yml file. This way we'd have a single place where to put all customisations.

**Comment by ShaneKilkelly** [comment]
@iacchi I agree that would be the best outcome, however, I think in this case we are running into a limitation of how the docker-compose `extends` keyword works. When it merges the configurations together, and encounters a multi-value key like `ports`, it _concatenates_ the two values together. (See https://docs.docker.com/compose/extends/#adding-and-overriding-configuration)

So in this case, docker-compose kept both the 80:80 value from the base configuration, plus your added value from the override file :(

**Comment by iacchi** [comment]
Oh. That may be a problem then, yes. What about removing that parameter from docker-compose.base.yml altogether, and add docker-compose.override.yml with that parameter (and any other multi-value parameters) among the other personalised config files created during the setup process as explained inside the quick-start guide? This way people will have that file there already, without needing to create one, and it'll contain already a set of useful parameters as a template, on which they can build. You can also think about removing docker-compose.base.yml altogether and put everything inside docker-compose.override.yml (many other web application use this route, where they have a template config file from which you have to remove the .template or something part of the filename to make it usable), but I don't know if you want to go that route, because then it won't auto-update with future releases if you need to change/add something to it. What I do know is that probably several people who have their own installation will want to mess around with ports, so maybe some parameters that are expected to change in a relatively high number of installation could go into docker-compose.override.yml

**Comment by ShaneKilkelly** [comment]
I've just merged the change to add the `SHARELATEX_PORT` option :)
