### ISSUE TITLE
Some problems while setting up: Overleaf command not found, 127.0.0.1 already in use etc.

### ISSUE THREAD

**Issue by singhakr** [overleaf/toolkit#137]
## Steps to Reproduce

1. I am trying to install Overleaf locally. Also I am trying as a non-root user but with sudo access. I have followed the toolkit guide. Initially, everything seems to go fine.
2. When I try bin/up, it says docker-compose not found. After some searching, I think the problem was that the docker-compose wrapper calls the command 'docker-compose', but for the version of Docker I installed, the right command is 'docker compose' (without the hyphen). After making this change in the exec line of the docker-compose wrapper file, bin/up seems to start correctly.

## Expected Behaviour

I should be able to use Overleaf as mentioned in the Toolkit Quick Start guide.

## Observed Behaviour

However, when I try to access http://localhost/launchpad, on the client side it says 403 Not Found. On the server side, containers started by bin/up shutdown, saying 127.0.0.1 is already in use, which is true.

## Context

I am not able to use Overleaf.

## Technical Info

* URL: N/A
* Browser Name and version: I tried using both Linux lynx command and Google Chrome.
* Operating System and version (desktop or mobile): Server side is Linux, Client side I tried both Linux and Windows 10.
* Signed in as: N/A
* Project and/or file: N/A

## Analysis

I think the Docker containers (with which I am not familiar) are trying to serve Overleaf on the default port 8080, but that port is already being used to serve the usual web pages. Perhaps the problem could be solved if I am able to run Overleaf on some other port and access that port to use Overleaf?

**Comment by singhakr** [comment]
While running bin/doctor, it also says:

> overleaf-toolkit/config/variables.env: line 1: Overleaf: command not found

This line in variables.env says:

> SHARELATEX_APP_NAME=Our Overleaf Instance

I am not sure what value should be put as the name of the Overleaf instance.

**Comment by singhakr** [comment]
An update:

Also, after changing 'exec docker-compose' to 'exec docker compose' in the docker-composes wrapper, if I run bin/doctor after changing the Overleaf instance name as 'sharelatex' as mentioned in the documentation, it says:

```
====== Warnings ======
! docker-compose not found
====== End ======
```

Another thing I tried was to change the port in lib/docker-compose.base.yml, but I think I will have to redo the init process after changing this file?

**Comment by singhakr** [comment]
So I did tried the following:

1. Removed the previous overleaf-toolkit directory and cloned the repository again.
2. Changed the port in lib/docker-compose.base.yml ports section to '${SHARELATEX_PORT:-1080}:80"' (I am not sure I am using valid numbers here).
3. Ran bin/init in this newly cloned directory.
4. Changed the first line of config/variables.env to put Overleaf instance name as: sharelatex
5. Changed the docker-compose 'exec docker-compose' to  'exec docker compose'.
6. Tried bin/up again. As non-root user, it says: permission denied. With sudo, it say: Error starting userland proxy: listen tcp4 127.0.0.1:80: listen: address already in use
7.  Ran sudo bin/doctor. It say: Warning: ! docker-compose not found

Note that the first docker-compose not found error was about the command docker-compose not being found.  In the first attempt after changing 'exec docker-compose' to 'exec docker compose', bin/up did seem to start, the second time it doesn't start at all. 

It seemed I was missing something simple. Since the port was changed, I checked currently running docker containers and found redis and mongo. I stopped them and tried sudo bin/up again. Now it seemed to run again, but when I tried to access launchpad, it stopped again with the same message that address already in use. Running bin/doctor still says docker-compose not found, but since it is a warning, I guess it may not matter.

It seems I am still missing something simple. Can someone suggest a solution? The Linux distribution is CentOS.

**Comment by singhakr** [comment]
Sorry for too many posts, but I should add one more bit of information. The service stops, it seems, with the error address already in use (without redis and mongo containers being stopped as it is not a proper shutdown) when I try to access anything on the client side, including the web server running on port 80.

**Comment by singhakr** [comment]
I was finally able to run it successfully, at least till starting the launchpad at 127.0.0.1 from command line using lynx from the server on which I installed it. It is so far not accessible from outside or using the domain name. This is most likely related to firewall  settings, although I have added the port 8080, which I am using now.

What I did was that I cloned the repository and then made changes in all the places in all the relevant files in lib/config-seed for changing port 80 to 8080. I also added the instance name as sharelatex. Finally, I changed the docker-compose 'exec docker-compose' to 'exec docker compose'.

Before doing the above and running bin/up, I removed the existing overleaf directory. Stopped all Docker containers and images and removed them, as given [here](https://www.geeksforgeeks.org/remove-all-containers-and-images-in-docker). 

Perhaps it might be useful for someone else who is not able to run with the usual method.

Thanks a lot for providing the source code. It will be very helpful for a book I am writing as I can't afford the Pro version right now and already have access to a VPS. I just need to collaborate with co-authors on the book.

**Comment by singhakr** [comment]
There were a few other glitches while finally being able to share with co-authors. One major problem was that the listen-to IP in configuration files (127.0.0.1) had to be changed to 0.0.0.0, otherwise it doesn't connect. This is a common problem, which I had faced while using WildFly server also. Not the best and secure solution, but it will do for the time being. 

Also, could not get email sending to work. Nor could I get SSL to work. There might be minor issues with these, but for now I am using without these two functions. Projects have to be shared via links sent manually, but it requires login in order to work using those link, so that's OK.

Read all the documentation I could find, followed all the instruction, and tried for a couple of days, but I must be missing something somewhere. Not familiar with how mail servers or SSL functionality works.

I do miss the tracking feature though and the Git syncing. But full history is still very useful.

One minor comment, just to check if it's a problem with my setup or a general limitation with CE version. Sometimes project compile fails completely. When that happens, I can just click clear cache button and then it compiles successfully.

**Comment by aeaton-overleaf** [comment]
Glad to hear you managed to get Overleaf Community Edition working 🙂

I think we can close this issue now, but feel free to open individual issues for any problems that still exist which other users might run into.

> `overleaf-toolkit/config/variables.env`: line 1: Overleaf: command not found
> `SHARELATEX_APP_NAME=Our Overleaf Instance`

Adding quotes around the value should fix the error, like this: `SHARELATEX_APP_NAME="Our Overleaf Instance"`

> changing `exec docker-compose` to `exec docker compose`

`alias docker-compose='docker compose'` will be the easiest way to resolve this, during the transition from compose v1 to v2 (I think Docker Desktop should set this up automatically).
