### ISSUE TITLE
On Safari Delete File and Directory in projects get 500 error, stuck and failed, tested with multiple server machines

### ISSUE THREAD

**Issue by ETOgaosion** [overleaf/toolkit#140]
## Steps to Reproduce

1. Follow the instructions in `quick-start-guide.md`, do `bin/init, bin/up, bin/start`
2. On Safari, open a project, touch a new file
3. delete the file, and we got this

![image](https://user-images.githubusercontent.com/57280232/223653337-2a469aee-321c-4f5c-ac8a-cf6ef6945a93.png)

## Expected Behaviour

On the official sites, file can easily be deleted by safari.

Files and directories can easily be deleted by chrome.

## Observed Behaviour

Some possible code snippets posted here:

![image](https://user-images.githubusercontent.com/57280232/223653556-c92a413e-6976-4bcd-b952-1606bceee65e.png)

this could lead to an 500 error code, like we catch in controller pad (same behavior on different machines):

![image](https://user-images.githubusercontent.com/57280232/223653806-de6f6fce-bc89-4a95-983b-6c926bcb4b1f.png)

## Context

It's disappointing that we cannot delete file, but only modify them, not full-functioned.

Thought there is some error on sharelatex image and I repull one in other machine, still fail, I think the source code shall have some problems.

## Technical Info

Just like code snippets above:

![image](https://user-images.githubusercontent.com/57280232/223653556-c92a413e-6976-4bcd-b952-1606bceee65e.png)

* URL:
* Browser Name and version: Safari
* Operating System and version (desktop or mobile): Intel Mac(2019), Self Hosted Server: Ubuntu 20.04
* Signed in as:
* Project and/or file:

## Analysis

Would you consider add or check app.delete doc/file/directory support for safari.

**Comment by jdleesmiller** [comment]
Thanks for the report. Could you confirm what version of the sharelatex image you are using here? Running the `bin/doctor` script in the toolkit should tell you this.

**Comment by mserranom** [comment]
@ETOgaosion would you mind also confirming the versions of macOS and Safari you're using? Thanks!
