### ISSUE TITLE
After setup instance is down for maintenance

### ISSUE THREAD

**Issue by Swaggeroo** [overleaf/toolkit#186]
## Steps to Reproduce

1. I normally setup it up with the toolkit
2. Added config for smtp
3. Upgraded TexLive to full

## Expected Behaviour

It should be working with no problem?

## Observed Behaviour

My instance now says that its down for Maintenance...
![image](https://github.com/overleaf/toolkit/assets/57057662/93edf391-4f07-480a-b731-0e6fca8fde75)
I also can't sign in anymore, the buttons at the top do nothing

## Context

I think there is maybe somewhere an option to toggle it on/off but I can't find it anywhere.

## Technical Info

* URL: N/A (local ip)
* Browser Name and version: Chrome 116.0.5845.112
* Operating System and version (desktop or mobile): desktop
* Signed in as: N/A
* Project and/or file: N/A

**Comment by Swaggeroo** [comment]
I tried reinstalling everything. I only kept the config folder. I created an admin account. After this I installed the full version of texlive. Than if I'm not logged in I get the same Maintenance screen. But if I'm still logged in I get this screen:![Screenshot_20230901_102217_Chrome.jpg](https://github.com/overleaf/toolkit/assets/57057662/61cf4385-685b-411f-9714-346f98b5199d)

**Comment by jko-nic** [comment]
I get also site in Maintenance mode, but I have figured it out. In your git directory of Overleaf Toolkit, type and run `bin/shell`, which will open a shell inside your docker container. Then edit file `/etc/sharelatex/site_status`, it contains only one line saying `closed`, so rewrite it to `open`. It should work now.

**Comment by Swaggeroo** [comment]
@jko-nic thanks a lot this fixed my issue
