### ISSUE TITLE
EPS Images are not displayed because epstopdf conversion file not generated

### ISSUE THREAD

**Issue by hartmannILA** [overleaf/toolkit#196]
When uploading a new eps image, overleaf is not showing the image in the pdf output. The log says that the package epstopdf did everything correct, but the eps-converter-to.pdf file is not found.

## Steps to Reproduce

1. Upload a new eps image
2. Put it in the document
3.Compile

## Expected Behaviour

The image should be displayed.

## Observed Behaviour

In the PDF just a black box is shown without the image.

## Context

We have to compile every eps first locally and the upload it.

## Technical Info

* URL: Own Overleaf Server
* Browser Name and version: Different Browsers
* Operating System and version (desktop or mobile): Ubuntu 22.04
* Signed in as: User
* Project and/or file:

**Comment by F-Depi** [comment]
I'm encountering the same issue. Even after the upgrade to a complete Texlive installation.

OS: Fedora Linux 38 (Workstation Edition)

**The exception** is that I hosted Overleaf locally for the first time 1 week ago and everything worked!

I deleted everything 2 days later (to reinstall everything setting up tls from the beginning) and I started getting the same error. 
I then deleted everything (repository, docker, Texlive) and reinstalled everything again twice, just for local hosting. But I'm still experiencing the same error.

**Comment by hartmannILA** [comment]
I did a comparable think. I had to set up the server for a 2nd time after the original server crashed completly after an update and the texlive installation was broken.

I looked in the log file. The package epstopdf says that it is generating the .pdf file, but the file is not stored.

**Comment by F-Depi** [comment]
### Solution? Upgrading path when upgrading TexLive
I believe I've identified the solution to the problem, or at least I've managed to successfully install everything and get it to work. When you're inside the shell (using bin/shell) after installing new packages (e.g., `tlmgr install scheme-full` or `tlmgr install <package-name>`), it's essential to execute the following command before exiting the shell:

`tlmgr path add`

I may not have the technical expertise to explain why this works, but given that epstofig often seems to encounter issues with image placement, occasionally putting images in the wrong folder without generating any errors or warnings, updating the path can likely help.

I found the solution in this pull request that was never accepted: #168. It clearly states that, when installing new packages from version 3.3.0, it's essential to run `tlmgr path add` afterwards.

**Comment by hartmannILA** [comment]
For me it looks like the adding the path also solved the problem. Thanks for the Information.
