### ISSUE TITLE
Changes to the environment variable configuration are not applied

### ISSUE THREAD

**Issue by dvmc** [overleaf/toolkit#20]
## Steps to Reproduce

1. Create a new Overleaf instance. (`bin/init`)
1. Make changes to the configuration files.
1. Run the instance. (`bin/start`)
1. Review environment variables in the docker container (`bin/shell`) with `env`.
1. Stop the instance. (`bin/stop`)
1. Make changes to the configuration files.
1. Start the instance again. (`bin/start`)
1. Review environment variables as above.

## Expected Behaviour

The new environment variables should appear. These are my configuration files:

### `overleaf.rc`

```
#### Overleaf RC ####

PROJECT_NAME=overleaf

# Sharelatex container
SHARELATEX_DATA_PATH=data/sharelatex
SERVER_PRO=false
SHARELATEX_PORT=127.0.0.1:6543

# Sibling Containers
SIBLING_CONTAINERS_ENABLED=false
DOCKER_SOCKET_PATH=/var/run/docker.sock

# Mongo configuration
MONGO_ENABLED=true
MONGO_DATA_PATH=data/mongo

# Redis configuration
REDIS_ENABLED=true
REDIS_DATA_PATH=data/redis
```

### `variables.env`

```
SHARELATEX_APP_NAME=Overleaf Example

ENABLED_LINKED_FILE_TYPES=url,project_file

# Enables Thumbnail generation using ImageMagick
ENABLE_CONVERSIONS=true

# Disables email confirmation requirement
EMAIL_CONFIRMATION_DISABLED=true

# temporary fix for LuaLaTex compiles
# see https://github.com/overleaf/overleaf/issues/695
TEXMFVAR=/var/lib/sharelatex/tmp/texmf-var

SHARELATEX_SITE_URL=https://server5.example.com:2025
SHARELATEX_NAV_TITLE=Overleaf Example
SHARELATEX_ADMIN_EMAIL=David.Michaelis@example.com

# pasted from https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx
SHARELATEX_SECURE_COOKIE=true
SHARELATEX_BEHIND_PROXY=true
```

### Other

There is no configuration file in `~/.docker` and I have tried to run the container with `env -u http_proxy -u https_proxy bin/start`. Therefore, I expect there to be no proxy configured.

## Observed Behaviour

The old environment variables are still there. Here's an excerpt from `env` within `bin/shell`:

```
HTTP_PROXY=http://squid.example.com:8080
LANG=en_US.UTF-8
WEB_API_USER=sharelatex
HOSTNAME=6a65d416a305
SHARELATEX_SECURE_COOKIE=true
SHARELATEX_SITE_URL=https://server5:2025
ENABLE_CONVERSIONS=true
SHARELATEX_CONFIG=/etc/sharelatex/settings.coffee
REDIS_HOST=redis
SHARELATEX_BEHIND_PROXY=true
PWD=/
HOME=/root
SHARELATEX_ADMIN_EMAIL=David.Michaelis@example.com
https_proxy=https://squid.example.com:8080
DEBIAN_FRONTEND=teletype
http_proxy=http://squid.example.com:8080
SHARELATEX_NAV_TITLE=Overleaf Example
no_proxy=*.example.com
NO_PROXY=*.example.com
HTTPS_PROXY=https://squid.example.com:8080
ENABLED_LINKED_FILE_TYPES=url,project_file
TERM=xterm
SHARELATEX_APP_NAME=Overleaf Example
EMAIL_CONFIRMATION_DISABLED=true
baseDir=.
SHLVL=1
LANGUAGE=en_US:en
SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex
TEXMFVAR=/var/lib/sharelatex/tmp/texmf-var
SHARELATEX_REDIS_HOST=redis
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2020/bin/x86_64-linux
LESSOPEN=| /usr/bin/lesspipe %s
OPTIMISE_PDF=true
_=/usr/bin/env
```

The `SHARELATEX_SITE_URL` is still the old one (without `.example.com`) and the proxies should not be configured at all.

## Context

I believe this to be the root cause of the problems described in overleaf/overleaf#802, because Redis and Mongo are trying to connect to localhost over the external proxy, which is destined to fail. However, I have not been able to update the environment variables yet.

## Technical Info

* URL: https://server5.example.com:2025/
* Browser Name and version: Firefox 81.0.2 (64-Bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04.6 LTS
* Signed in as:
* Project and/or file:

**Comment by ShaneKilkelly** [comment]
Thanks for the detailed bug report!

I think this is because `start` and `stop` will not recreate an existing container, so the environment changes won't be applied. However, `bin/up` _will_ recreate the container and apply the environment changes.

Would you mind running `bin/stop`, then `bin/up` and seeing if that works?

**Comment by ShaneKilkelly** [comment]
I've also noticed that `bin/up` does not pass any flags along to the `docker-compose` program, so passing `-d` does not run it in detached mode. I'll fix this too :+1:

**Comment by dvmc** [comment]
> However, `bin/up` _will_ recreate the container and apply the environment changes.

Thanks, that was the hint! After reading the quick start guide, I've had assumed that the only difference between `bin/start` and `bin/up` was that the former does not attach to the logs. Overleaf is working now.

**Comment by ShaneKilkelly** [comment]
Wonderful! And we've just merged a change to the `bin/up` script, which allows you to pass docker-compose flags to it. So for example, `bin/up -d` will start in detached mode, just like `bin/start`.
