### ISSUE TITLE
How to make local instance of overleaf working for Chinese?

### ISSUE THREAD

**Issue by johnbao6** [overleaf/toolkit#209]
I try to make a local overleaf server for our college's student. It should work under Chinese enviroment and CTEX.

I have tried Overleaf Toolkit for a week, but still have no idea. There very few document about International setting.

**Comment by Musicminion** [comment]
参考这个链接：https://github.com/overleaf/overleaf/wiki/i18n-Languages

修改env文件
```
SHARELATEX_SITE_LANGUAGE=zh-CN
```

**Comment by johnbao6** [comment]
谢谢，
我在 env 文件中添加这一行，但是不起作用，我重启服务器也不行，还有什么地方需要注意的？

**Comment by Musicminion** [comment]
不可能啊，我都是这样配置的，你要在`config/variables.env`里面修改哦！

**Comment by Past-GuoWang** [comment]
> 不可能啊，我都是这样配置的，如果你用的就是[toolkit](https://github.com/overleaf/toolkit/)部署的，你先运行`bin/init`，然后在`config/variables.env`里面修改哦！添加一行新的内容。
> 
> ```shell
> SHARELATEX_SITE_LANGUAGE=zh-CN
> ```
> 
> 当然，部分界面翻译没更新（所以你看到的是半中文、半英文的界面，这是正常现象），因为距离上次更新中文翻译已经过了两年多了，期间也没什么人维护中文部分的翻译。
> 
> 我自己部署的中文界面（
> 
> <img alt="截屏2024-01-19 15 14 13" width="1389" src="https://private-user-images.githubusercontent.com/84625273/297983164-c08c716c-5c00-41cb-bf99-7f0f84c72fce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzk5MDEsIm5iZiI6MTcwNjMzOTYwMSwicGF0aCI6Ii84NDYyNTI3My8yOTc5ODMxNjQtYzA4YzcxNmMtNWMwMC00MWNiLWJmOTktN2YwZjg0YzcyZmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA3MTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzdiY2JhYzVhYTU3MWIxZTQ4ZDZmMDhiZmI3ZGFjNDRkNDRkNjkwZmY3NzNhODIwZmE2Y2RmNTVhYzVmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q4gjTqgS29xAiI21rYPcguhUuOUkatTOFPuV4ace-EQ">
> 补充一句，现在 Overleaf的中文本地化已经推到接近100%了，[官网](https://cn.overleaf.com/)目前也更新了中文界面（当然由于我翻译的时候，很多时候看不到原界面对应的东西，翻译可能有些生硬粗糙，目前正在修改不妥的地方、broken link等之类的），社区版预计等下一个版本会把更新拉入。如果觉得有任何翻译上不妥的地方可以告诉我看看如何修改~

直接使用了docker-compose.yml进行安装的话，应该如何设置中文呢，找不到variables.env

**Comment by Past-GuoWang** [comment]
> > 不可能啊，我都是这样配置的，如果你用的就是[toolkit](https://github.com/overleaf/toolkit/)部署的，你先运行`bin/init`，然后在`config/variables.env`里面修改哦！添加一行新的内容。
> > ```shell
> > SHARELATEX_SITE_LANGUAGE=zh-CN
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当然，部分界面翻译没更新（所以你看到的是半中文、半英文的界面，这是正常现象），因为距离上次更新中文翻译已经过了两年多了，期间也没什么人维护中文部分的翻译。
> > 我自己部署的中文界面（
> > <img alt="截屏2024-01-19 15 14 13" width="1389" src="https://private-user-images.githubusercontent.com/84625273/297983164-c08c716c-5c00-41cb-bf99-7f0f84c72fce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzk5MDEsIm5iZiI6MTcwNjMzOTYwMSwicGF0aCI6Ii84NDYyNTI3My8yOTc5ODMxNjQtYzA4YzcxNmMtNWMwMC00MWNiLWJmOTktN2YwZjg0YzcyZmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA3MTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzdiY2JhYzVhYTU3MWIxZTQ4ZDZmMDhiZmI3ZGFjNDRkNDRkNjkwZmY3NzNhODIwZmE2Y2RmNTVhYzVmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q4gjTqgS29xAiI21rYPcguhUuOUkatTOFPuV4ace-EQ">
> > 补充一句，现在 Overleaf的中文本地化已经推到接近100%了，[官网](https://cn.overleaf.com/)目前也更新了中文界面（当然由于我翻译的时候，很多时候看不到原界面对应的东西，翻译可能有些生硬粗糙，目前正在修改不妥的地方、broken link等之类的），社区版预计等下一个版本会把更新拉入。如果觉得有任何翻译上不妥的地方可以告诉我看看如何修改~
> 
> 直接使用了docker-compose.yml进行安装的话，应该如何设置中文呢，找不到variables.env

好了，我直接写到了环境变量里面，问题已经解决了

**Comment by johnbao6** [comment]
非常感谢，现在可以了。
