### ISSUE TITLE
Data migration

### ISSUE THREAD

**Issue by blue-eyed-g** [overleaf/toolkit#230]
I reinstalled Overleaf and exported the previous 'data' folder. Can I just replace the new 'data' folder with the old one? How can I import my previous data?

**Comment by mserranom** [comment]
You can do it, as long as you're running the same version of Overleaf CE/Server Pro.

**Comment by blue-eyed-g** [comment]
> You can do it, as long as you're running the same version of Overleaf CE/Server Pro.

ok, thanks
