### ISSUE TITLE
compose structure seems not to work, only starts mongo container

### ISSUE THREAD

**Issue by afmart** [overleaf/toolkit#272]
## Steps to Reproduce

1. Install docker engine on Alma Linux 9 
2. Clone repository to /opt/overleaf-toolkit
3. Go into /opt/overleaf-toolkit and run bin/init
4. Run bin/up 
5. Only "mongo" container is downloaded and created

## Expected Behaviour

It should create all needed containers! 

## Observed Behaviour

![image](https://github.com/user-attachments/assets/0002aa00-300e-4640-a567-32c1dfd2fe82)
![image](https://github.com/user-attachments/assets/aedd0227-80e9-4b98-944b-c77c7ce6a743)

Running the "init" or "start" command only downloads the image  and creates the database container "mongo"

## Context

Following the quick guide we can't deploy overleaf.  

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile): Alma Linux 9.3
* Signed in as: 
* Project and/or file:

## Analysis

====== Overleaf Doctor ======
- Host Information
    - Linux
    - lsb_release not found !
- Dependencies
    - bash
        - status: present
        - version info: 5.1.8(1)-release
    - docker
        - status: present
        - version info: Docker version 27.0.3, build 7d4bcd8
    - realpath
        - status: present
        - version info: realpath (GNU coreutils) 8.32
    - perl
        - status: present
        - version info: 5.032001
    - awk
        - status: present
        - version info: GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0-p9, GNU MP 6.2.0)
    - openssl
        - status: present
        - version info: OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
    - docker compose
        - status: present
        - version info: Docker Compose version v2.28.1
- Docker Daemon
    - status: up
    - server version: 27.0.3
====== Configuration ======
- config/version
    - status: present
    - version: 5.1.0
- config/overleaf.rc
    - status: present
    - values
        - OVERLEAF_DATA_PATH: data/overleaf
        - SERVER_PRO: false
        - OVERLEAF_LISTEN_IP: 127.0.0.1
        - OVERLEAF_PORT: 80
        - MONGO_ENABLED: true
        - MONGO_IMAGE: mongo
        - MONGO_DATA_PATH: data/mongo
        - REDIS_ENABLED: true
        - REDIS_IMAGE: redis:6.2
        - REDIS_AOF_PERSISTENCE: true
        - REDIS_DATA_PATH: data/redis
        - NGINX_ENABLED: false
        - NGINX_CONFIG_PATH: config/nginx/nginx.conf
        - TLS_PRIVATE_KEY_PATH: config/nginx/certs/overleaf_key.pem
        - TLS_CERTIFICATE_PATH: config/nginx/certs/overleaf_certificate.pem
        - NGINX_HTTP_LISTEN_IP: 127.0.1.1
        - NGINX_HTTP_PORT: 80
        - NGINX_TLS_LISTEN_IP: 127.0.1.1
        - TLS_PORT: 443
        - GIT_BRIDGE_ENABLED: false
- config/variables.env
    - status: present
    - values
        - SHARELATEX_FILESTORE_BACKEND: fs
        - SHARELATEX_HISTORY_BACKEND: fs
        - OVERLEAF_FILESTORE_BACKEND: fs
        - OVERLEAF_HISTORY_BACKEND: fs
====== Warnings ======
- None, all good
====== End ======

**Comment by zhuohaoyu** [comment]
Same problem, looks like they made it impossible for CE to run.

**Comment by vidlb** [comment]
So the issue seems that it should be false by default (and as stated in the docs), but the init script will produce a true value even though PRO is false.

**Comment by Karonolandiis** [comment]
> Thanks to @Tunfisch96 comment about last usable commit, I read the diff and found out this is linked to the new env variable SIBLING_CONTAINERS_ENABLED. The doc [here](https://github.com/overleaf/toolkit/blob/master/doc/overleaf-rc.md) states that it requires `SERVER_PRO=true`. It looks like `SERVER_PRO=false` + `SIBLING_CONTAINERS_ENABLED=true` will prevent docker to pull and run images. Setting `SIBLING_CONTAINERS_ENABLED=false` in overleaf.rc fixed it for me !
> 
> So the issue is simply that the init seed value for this variable should be false, as stated in the docs.

That so cool! Thank you very much!!!

**Comment by das7pad** [comment]
Thanks for flagging this up. https://github.com/overleaf/toolkit/pull/276 should fix this issue. You can use `bin/upgrade` to pull in these changes. Sorry for any inconvenience this has caused.
