### ISSUE TITLE
Unable to run with a saved sharelatex image

### ISSUE THREAD

**Issue by vidlb** [overleaf/toolkit#275]
Following the docs in [doc/ce-upgrading-texlive.md](https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md), I'm trying to commit image with installed packages, but this is not working : 
```bash
❯ docker commit sharelatex sharelatex/sharelatex:5.1.0-custom
sha256:1c2e7d483b57a5361dadc0d836c9b2c7ce0df67b07006e2cd6e726ed197e89b7
❯ bin/docker-compose down
❯ echo "5.1.0-custom" > config/version
❯ bin/up -d
ERROR: invalid version '5.1.0-custom'
```

I was forced to commit my image using the current tag "5.1.0" in order to make it work.  
May be this is because of my docker version, (almost latest) ?

```
Client: Docker Engine - Community
 Version:    27.0.3
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
```

**Comment by ThexXTURBOXx** [comment]
It definitely works since https://github.com/tuetenk0pp/sharelatex-full successfully builds.
If you just want a Docker image with all packages installed, just use that one instead :)

**Comment by vidlb** [comment]
Well... it's definitively not working without modifying the compose config. 

I don't want a "full" or exotic image, just to be able to change the state of my container as advertised in the docs, with few packages installed, and using the official docker image.  
Thanks for the suggestion, not saying it doesn't work with a different image, yet it doesn't work if you follow the docs, thus I believe this issue is legit.

**Comment by ThexXTURBOXx** [comment]
Try to follow this state of the guide: https://github.com/overleaf/toolkit/blob/c8fc9c5932fb4148bc31d83838e3bb81c1930f12/doc/ce-upgrading-texlive.md
If that also does not work, the issue is definitely on your end, as everything works fine on mine.

**Comment by vidlb** [comment]
All right I found out why this isn't working with `"5.1.0-custom"`: it turns out there is a regex match for the image version in https://github.com/overleaf/toolkit/blob/master/lib/shared-functions.sh .  
It only allows version ending with "-with-texlive-full".  

And here I was saying I followed the docs.. not close enough it seems.
