### ISSUE TITLE
Docker image can not run arm64 pi(ubuntu 20.04LTS)

### ISSUE THREAD

**Issue by chu278** [overleaf/toolkit#28]
This image is based on x86-64 device.
But did not work on arm64 device because of architecture.

Error showed in running process:  standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by gh2k** [comment]
Thanks for the report. Unfortunately, we don't plan to support an arm image at this time.

**Comment by random-logic** [comment]
While not officially supported, I built the sharelatex image for ARM and uploaded it to DockerHub. Got it working on my ARM based Mac. You would have to pull from randomlogic01/sharelatex
