### ISSUE TITLE
It can not start at all!

### ISSUE THREAD

**Issue by Cufoon** [overleaf/toolkit#289]
## Steps to Reproduce

1. clone the repo
2. exec `bin/init`
3. change the `overleaf.rc` in `config`
```
10,11c10,11
< OVERLEAF_LISTEN_IP=127.0.0.1
< OVERLEAF_PORT=80
---
> OVERLEAF_LISTEN_IP=0.0.0.0
> OVERLEAF_PORT=5080
```
5. then run `bin/up`

## Expected Behaviour

just run

## Observed Behaviour

could not be used normally

## Logs

[logs.txt](https://github.com/user-attachments/files/16885838/logs.txt)

**Comment by guilhas07** [comment]
What OS are you using? I had the same problem while trying to set up in wsl with `networkingMode=mirrored` enabled in `.wslconfig` .

**Comment by Cufoon** [comment]
> What OS are you using? I had the same problem while trying to set up in wsl with `networkingMode=mirrored` enabled in `.wslconfig` .

I am using ubuntu server 22.04 lts.

**Comment by das7pad** [comment]
Hello,

Thank you for opening this issue. Are you able to connect to it locally without the address/port changes? There might be a firewall in place that is blocking access to that port.

Greetings,
Jakob

**Comment by lightshark85** [comment]
Debian Server - same issue with mongoDB as in his logs (no firewall - changed nothing in the config)

**Comment by Cufoon** [comment]
I have used another new ubuntu server vm, the problem solved. BUT I still not know why this error happen.
