### ISSUE TITLE
Tex packages missing

### ISSUE THREAD

**Issue by 92sherlock** [overleaf/toolkit#32]
Recently deployed overleaf to a linode server using this link:
https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md
but i want to know how to install full latex packages since some projects do not have certain packages.

**Comment by ShaneKilkelly** [comment]
Hi!

You can find documentation on installing texlive packages here: https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md

**Comment by 92sherlock** [comment]
Thanks you. Got it figured out. The procedure did not work for me

But I would like to know if I could a procedure for install ssl on my
linode server and domain name
Best Regards

Kwame Owusu Edusei AMIMA
PhD Candidate
National Institute for Mathematical Sciences (NIMS)
Center for Scientific and Technical Computing
PMB, KNUST- Kumasi, Ghana
E: koedusei@nims.edu.gh// <https://muphi.hw.ac.uk/people/>
92sherlock@gmail.com
T : 0501090447/0543257933
W : http://www.nims.edu.gh/about
<http://www.nims.edu.gh/about-nims/graduate_students/kwame-owusu-edusei>
nims/graduate_students/kwame-owusu-edusei
<http://www.nims.edu.gh/about-nims/graduate_students/kwame-owusu-edusei>
   https://muphi.hw.ac.uk/people
