### ISSUE TITLE
Grunt install is not working to download other repos from toolkit

### ISSUE THREAD

**Issue by lacraft** [overleaf/toolkit#34]
## Steps to Reproduce

1. clone the overleaf toolkit repo
2. grunt install
3.

## Expected Behaviour

I expected to be able to use grunt install to install the other repositories to allow editing on them
## Observed Behaviour

grunt install is not working for me 
## Context

I would like to be able to work with the document-updater repo and edit it on my local instance of overleaf for research for my masters thesis
## Technical Info

I may be missing something on my end for grunt install to work. I mainly need to know if it is possible to install and work on the other overleaf repositories from overleaf/toolkit like it is stated from overleaf/overleaf

thanks!
* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by mpsdskd** [comment]
I _might_ have the same problem and just found your issue,not sure, though.

What's your error message?

**Comment by lacraft** [comment]
I was getting the error that grunt is not installed locally for this project

**Comment by lacraft** [comment]
> I _might_ have the same problem and just found your issue,not sure, though.
> 
> What's your error message?

I was getting the error that grunt is not installed locally for this project

**Comment by lacraft** [comment]
Is there an instruction manual somewhere that covers how to locally install and run overleaf with desired extra repositories?

**Comment by ShaneKilkelly** [comment]
Hi there! The overleaf toolkit does not use grunt. I believe we used to use grunt in a legacy repo, which is not supported any more. 

The instruction manual for getting started with the toolkit is in the [Quick Start Guide](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md) We don't officially support the old method of running every service locally.
