### ISSUE TITLE
Mongo connection loop

### ISSUE THREAD

**Issue by tdiethe** [overleaf/toolkit#35]
## Steps to Reproduce

This had been been running ok for the last two months or so. I noticed the server was down, so logged into the box to see what was going on. The process had stopped, so I tried running `bin/up`.

## Expected Behaviour
Expected the server to start

## Observed Behaviour
It seems that mongo is getting stuck in a loop of connecting and disconnecting - see below:

![image](https://user-images.githubusercontent.com/1110560/105726391-ef670e00-5f21-11eb-88fa-002b93ed6d1e.png)

**Comment by ShaneKilkelly** [comment]
Hi there!

I suspect the Mongo instance has been upgraded somehow, and may be running a version of  mongo not compatible with Overleaf. 

Could you run `bin/doctor` and paste the output here? Thanks!

**Comment by ShaneKilkelly** [comment]
Thanks! 

And could you check the output of `bin/docker-compose exec mongo bash -c 'mongo --version' ` ? 

Plus, could you check `bin/error-logs web`, and see if the web server process is showing any other errors?

**Comment by tdiethe** [comment]
```
MongoDB shell version v3.6.20
git version: 39c200878284912f19553901a6fea4b31531a899
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
```

**Comment by ShaneKilkelly** [comment]
Ok, that looks like the right version of mongo for your version of overleaf. 

Could you check the output of `bin/error-logs web`?

**Comment by tdiethe** [comment]
Oh sorry missed that ... there's no output at all from there. 

Update - we rebooted the server, and restarted everything, and now seems to be working. Sorry I can't help get to the bottom of this!
