### ISSUE TITLE
Creating Project Templates for the Group

### ISSUE THREAD

**Issue by directorfury192** [overleaf/toolkit#42]
Is there a way, similar to how we access templates on the www.overleaf.com, that we can take a project template and have it accessible for anyone on our CE server to create a project from?  e.g., report templates for our organization.

**Comment by ShaneKilkelly** [comment]
Hi there! I believe this page covers what you need: https://github.com/overleaf/overleaf/wiki/Server-Pro:-Setting-up-templates

If not, just let me know :+1:

**Comment by directorfury192** [comment]
Is this true for the overleaf CE version too?
