### ISSUE TITLE
Problem in bin/doctor script awk version detection

### ISSUE THREAD

**Issue by lordwolfchild** [overleaf/toolkit#44]
## Steps to Reproduce

Calling bin/doctor on Debian Buster default installs fails due to awk error:

```
[...]
- Dependencies
[...]
    - awk
        - status: present
awk: not an option: --version
```
## Expected Behaviour

I would expect the doctor script to output the awk version correctly.

## Technical Info

/bin/doctor assumes that gawk variant is installed and selected as standard awk-variant. The assumption that this variant is available fails with standard Debian installations (and Ubuntu, too, if I remember right), as the standard awk-variant there is mawk, which has no '--version' parameter.

## Analysis

I worked around the problem by installing gawk and selecting it as the system standard via update-alternatives.

This bug can be fixed by not assuming that gawk responds when calling 'awk'. The --version parameter is gawk specific; a better variant for version analysis is looking at the output of 'awk -W version', which works on both (and maybe some more) variants.

**Comment by gh2k** [comment]
This should be fixed alongside #45 so will close here.
