### ISSUE TITLE
Provide support for running in detached mode

### ISSUE THREAD

**Issue by synergiator** [overleaf/toolkit#6]
Typically, for longer operation you would run in detached mode:

```
docker-compose ... -d
```
Passing this to bin/up did not work; I added this as default in the end of the wrapper (bin/docker-compose).

**Comment by ShaneKilkelly** [comment]
Thanks for the suggestion! 

I'm surprised that the `-d` flag doesn't currently work. I'll investigate why that might be. In the mean-time, `bin/start` might be a useful tool, as it will start the containers in the background by default.

**Comment by ShaneKilkelly** [comment]
Closing this issue for now, we can re-open if any further issues come up.
