### ISSUE TITLE
How to restart/stop the Docker context?

### ISSUE THREAD

**Issue by synergiator** [overleaf/toolkit#7]
Currently, I don't see how to tell the docker-compose wrapper script to restart either stop the service.

Especially restarting is essential in the try out phase while tuning config files. I like the toolkit indeed very much! Quite complex service environment as turnkey script: nice. :-)

My current workaround for restarting: restart the Docker daemon  service of the test machine.

**Comment by ShaneKilkelly** [comment]
Hi there!

Running `bin/docker-compose restart`should accomplish what you want. Or, you could use `bin/stop` and `bin/start` separately.

If you encounter an error while running any of these scripts, could you post the error message here please? :) 

Also, it would be useful if you could run `bin/doctor` and paste the output here too. Thanks!

**Comment by synergiator** [comment]
works, thank you!

**Comment by rmozul** [comment]
Hello,

I know I am late, but I feel that my remark is, while not completely related to this issue, not worthy of the opening of a whole new issue.

I found that it was not straightforward, either, reading the `doc/quick-start-guide.md` or the `doc/configuration.md`, that the `variables.env` file is read only when doing  the first `./bin/up` .

I made some stupid mistakes in my file, and my only way to reload it was to:
```shell
./bin/stop
docker container prune
./bin/up
```

Anyway, thanks a lot for this great tool !!!
