### ISSUE TITLE
Question regarding horizontal scaling

### ISSUE THREAD

**Issue by synergiator** [overleaf/toolkit#8]
Hi there - what about distributed deployments? 

Docker compose on which the toolkit is based allows afaik using Docker Swarm for that, but its future is [not clear](https://medium.com/@markuman/is-docker-swarm-mode-eol-7a3f316116a3)? That is, is Overleaf not suitable for horizontal scaling, or will be there support for k8s?

If there should be no problems with deploying Overleaf on Docker Swarm, how does the toolkit being docker compose wrapper address container scaling in terms of multiple replicas?

**Comment by ShaneKilkelly** [comment]
I don't think the toolkit (or even the docker image that the toolkit uses) is suitable for horizontal scaling, unfortunately. It runs all of the overleaf services inside one container, with the assumption that the container can be treated as a fully self-contained "appliance". 

This is something we'll keep in mind for future iterations, but I can't promise any change in the short or medium term.

**Comment by synergiator** [comment]
@ShaneKilkelly 

>  "It runs all of the overleaf services inside one container,"

How do you mean, are there many more other services? At least mongo DB and redis run separately as far as I can see. Is that less relevant for horizontal scaling?

```
> docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                    PORTS                NAMES
b28499623771        sharelatex/sharelatex:2.4.1   "/sbin/my_init"          2 hours ago         Up 1 second               0.0.0.0:80->80/tcp   sharelatex
96e67f265925        mongo:3.6                     "docker-entrypoint.s…"   2 hours ago         Up 11 seconds (healthy)   27017/tcp            
mongo
f3b8d9ed67eb        redis:5.0                     "docker-entrypoint.s…"   2 hours ago         Up 12 seconds             6379/tcp             redis

```

**Comment by ShaneKilkelly** [comment]
Ah, by "services"  I mean the various micro-services that make up the Overleaf stack. Because we jam them all into a single docker image, we can treat the "sharelatex" image as a single docker-level service, which is actually composed of many smaller parts internally. 

For example, `bin/docker-compose exec sharelatex bash -c 'ls -la /var/www/sharelatex'` will show a list of the various micro-services running inside the `sharelatex` container
