### ISSUE TITLE
How to set up TLS when port 443 is already used

### ISSUE THREAD

**Issue by MarkWieczorek** [overleaf/toolkit#80]
I have installed overleaf using the toolkit, and everything works fine when I access it via http. However, I would like to set this up to use https so that I could access my overleaf instance remotely. The problem is that I am already using ports 80 and 443 for a nextcloud instance.

I thought that it would be trivial to change the ports in the config files to use another port, but I have not been able to get this to work. When accessing my server on my local network with the new port, I simply get redirected to `127.0.0.1` on my local machine (not the machine where overleaf is installed). I don't fully understand how nginx works, and that might be part of my problem.

What I did was the following: 

In `config/overleaf.rc`, I changed `SHARELATEX_LISTEN` to 127.0.0.1 with the port 2500. I enabled NGINX, changed the HTTP/HTTPS ports to 8888/8443, and set `NGINX_TLS_LISTEN_IP` to 0.0.0.0, with `NGINX_HTTP_LISTEN` to 127.0.1.1.

In addition to this, I uncommented the two TLS lines in `config/variables.rc` Finally, in `config/nginx/nginx.conf`, I changed the port number `http://sharelatex:2500` to match what I used for `SHARELATEX_PORT`.

I have tried a million permutations, and haven't been able to get this to work. Even if I am doing something really dumb, it probably would be a good idea to improve the documentation for people like me.

## Steps to Reproduce
`config/overlear.rc`

```
#### Overleaf RC ####

PROJECT_NAME=overleaf

# Sharelatex container
SHARELATEX_DATA_PATH=data/sharelatex
SERVER_PRO=false
SHARELATEX_LISTEN_IP=127.0.0.1
SHARELATEX_PORT=2500

# Sibling Containers
SIBLING_CONTAINERS_ENABLED=false
DOCKER_SOCKET_PATH=/var/run/docker.sock

# Mongo configuration
MONGO_ENABLED=true
MONGO_DATA_PATH=data/mongo

# Redis configuration
REDIS_ENABLED=true
REDIS_DATA_PATH=data/redis

# TLS proxy configuration (optional)
# See documentation in doc/tls-proxy.md
NGINX_ENABLED=true
NGINX_CONFIG_PATH=config/nginx/nginx.conf
NGINX_HTTP_PORT=8888
# Replace these IP addresses with the external IP address of your host
NGINX_HTTP_LISTEN_IP=127.0.1.1
NGINX_TLS_LISTEN_IP=0.0.0.0
TLS_PRIVATE_KEY_PATH=config/nginx/certs/overleaf_key.pem
TLS_CERTIFICATE_PATH=config/nginx/certs/overleaf_certificate.pem
TLS_PORT=8443
```

`config/nginx/nginx.conf`
```
events {}

http {

    server {
        listen 80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }


    server {
        listen 443 ssl;

        ssl_certificate      /certs/nginx_certificate.pem;
        ssl_certificate_key  /certs/nginx_key.pem;

        ssl_protocols               TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers   on;

        # used cloudflares ciphers https://github.com/cloudflare/sslconfig/blob/master/conf
        ssl_ciphers                 EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;

        # config to enable HSTS(HTTP Strict Transport Security) https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
        # to avoid ssl stripping https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";

        server_tokens off;

        client_max_body_size 50M;

        location / {
            proxy_pass http://sharelatex:2500; # The port must match the value of SHARELATEX_PORT.
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 3m;
            proxy_send_timeout 3m;
        }
    }
}
```

**Comment by YinAoXiong** [comment]
@MarkWieczorek 
Changing 
`proxy_pass http://sharelatex:2500;`
 to
`proxy_pass http://sharelatex:80;`
may solve your problem.
The principle is explained in #81

**Comment by MarkWieczorek** [comment]
Thanks. I made all the changes in your pull request (https://github.com/overleaf/toolkit/pull/81) and it now works!
