### ISSUE TITLE
Upgrade to a complete TeXLive installation

### ISSUE THREAD

**Issue by tdiethe** [overleaf/toolkit#9]
On the [main quick start guide](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#latex-environment) the instructions say:

```
LaTeX environment
To save bandwidth, the Overleaf image only comes with a minimal install of TeXLive. To upgrade to a complete TeXLive installation, run the installation script in the Overleaf container with the following command:

$ docker exec sharelatex tlmgr install scheme-full
Alternatively you can install packages manually as you need by replacing scheme-full with the package name.

Note that these changes made inside the sharelatex container with docker exec are ephemeral --- they will be lost if Compose recreates the container. To make them persistent, you can use docker commit:

docker commit sharelatex sharelatex/sharelatex:with-texlive-full
Then edit your docker-compose.yml to use that image:

# ...
services:
    sharelatex:
        image: sharelatex/sharelatex:with-texlive-full
# ...
```

When using the toolkit, how do you make the changes persistent - I can't find where the docker-compose.yml is stored?

**Comment by tdiethe** [comment]
Ok found a solution. Putting "with-texlive-full" into config/version seemed like it might work, but bin/docker-compose checks the format of the version. My solution to this was to add a second line to the config file and update bin/docker-compose as follows (renamed to .txt to allow upload):
[docker-compose.txt](https://github.com/overleaf/toolkit/files/5242170/docker-compose.txt)

**Comment by lh-astro** [comment]
I think this is related. When I run:
```
sudo docker exec sharelatex tlmgr install scheme-full 
```
I get:
```
/usr/local/texlive/2020/bin/x86_64-linux/tlmgr: TLPDB::from_file could not initialize from: http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb
/usr/local/texlive/2020/bin/x86_64-linux/tlmgr: Maybe the repository setting should be changed.
/usr/local/texlive/2020/bin/x86_64-linux/tlmgr: More info: https://tug.org/texlive/acquire.html
```
What should I do to get the `scheme-full` version?

**Comment by lh-astro** [comment]
I figures out the problem. The sharlatex container had no connection to the internet.

**Comment by ShaneKilkelly** [comment]
For future reference, we have also updated the documentation on how to persist a texlive upgrade in CE: https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md

**Comment by dzhuang** [comment]
The tag `with-texlive-full` does not exist.

**Comment by maxperso** [comment]
> I think this is related. When I run:
> 
> ```
> sudo docker exec sharelatex tlmgr install scheme-full 
> ```
> 
> I get:
> 
> ```
> /usr/local/texlive/2020/bin/x86_64-linux/tlmgr: TLPDB::from_file could not initialize from: http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb
> /usr/local/texlive/2020/bin/x86_64-linux/tlmgr: Maybe the repository setting should be changed.
> /usr/local/texlive/2020/bin/x86_64-linux/tlmgr: More info: https://tug.org/texlive/acquire.html
> ```
> 
> What should I do to get the `scheme-full` version?

Exactly what I need for full installation on macos thanks !

**Comment by Logicbloke** [comment]
You can also run `bin/shell` and then run `tlmgr install scheme-full`.

Then you can commit using the aforementioned `docker commit` command and save it to `config/version`.
