### ISSUE TITLE
How to Manage Users for Localhost Overleaf ?

### ISSUE THREAD

**Issue by zwxlyy1995** [overleaf/toolkit#96]
Hello, I'm deploying a overleaf instance on my own device, and I can login on another device in the same local networks. I can register new users for my team as admin. But I dont know how to manage them. What I want to do is to query all users (whether it's able to see detailed information) and delete some users. Any Help ?

**Comment by IceGiraffe** [comment]
I think you can query and manage all users in database container. I've found infomation of users exists in MongoDB container.

**Comment by zwxlyy1995** [comment]
Hi, Ice

As you said，I can query all users' information stored in MongoDB.

Thank you.
