### ISSUE TITLE
Review and Comment function is missing?

### ISSUE THREAD

**Issue by ZayneHuang** [overleaf/toolkit#99]
Thanks for your nice work!

## Steps to Reproduce
1. I installed the overleaf community edition (toolkit) as the guide suggests. The system is running well.
2. I created a project and shared it with one of the team members.
3. The review and comment function is still not visible in the project interface.

## Expected Behaviour

As shown in the project teaser, the comment and review function should exist.

## Observed Behaviour

The comment and review functions are not visible.

## Context

It is hard to collaborate with team members.
Or maybe it is not available for the community edition?

**Comment by mserranom** [comment]
Review and Comment features are only available in Overleaf Server Pro: https://www.overleaf.com/for/enterprises/features


> As shown in the project teaser

If you mean the screenshot in https://github.com/overleaf/overleaf, we've updated it to display an Overleaf CE image.
